name: Docker Image CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:

jobs:

  build:
    name: Build Docker image
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build ./frontend/docker --file Dockerfile --tag nftkz-ft:dev
      - name: Push the Docker image
        run: docker push localhost:5000/nftkz-ft:dev
    
